Introduce Initial Code Generation
vldF/i-lang-compiler pull request #5
Opened 2024-03-16 19:20 UTC by vldF

Поменял структуру тестов и добавил тесты для кодогенерации. Теперь структура выглядит очевиднее так как файлы
 с логикой не мешаются с файлами с тестами. Кодгенератор теперь знает не про имя тест-раннера, а про 
конкретный инстанс класса. Это поможет при рефакторингах держать код неразломаным.

Тесты кодгенерации выглядят сложными, но работают следующим образом:

1. Парсим программу, получаем IR представление и запускаем проверки/анализ на них — в данный момент нужен 
только анализ завершаемости блоков, но возможно, что в будущем будет что-то ещё.

2. Генерируем IR LLVM при помощи класса-генератора `CodeGenerator`. В нём есть функция для компиляции представления в объектный файл, она работает, но не нужна сейчас. Оставил её на будущее.

4. После генерации происходит валидация функций и модуля. Если она падает, то выводится на экран какое-то описание проблемы и исключение бросается. Еще, выводится текстовое представление IR в консоль. К сожалению, сложно его вытащить как-то адекватно, у библиотеки LLVM просто нет такой функции. Есть еще функции для просмотра CFG, но их нельзя настроить никак и они просто открывают dot файл в приложении по-умолчанию в системе — там какая-то ерунда была все разы пока я смотрел, наверное, это бесполезно.

6. Из файла с исходником для теста считывается мета-информация для запуска теста. Решил её хранить прямо в файле с исходником, так как это не будет создавать кучу файлов (если бы я хранил её в отдельных файлах) и при этом и код, и данные видны на одном экране сразу же. Формат следующий: `имя_функции(аргумент1, аргумент2, ...)[: возвращаемый_результат]`. Доступны только примитивные типы, добавить пользовательские можно, но не хочется. Если возвращаемый тип не указан, то считаем, что там `unit`. Можно указать несколько таких строчек, тогда тест будет запущен для каждой из них. Если нет ни одной, то при тесте просто проверится, что никаких исключений при генерации кода не было (сейчас они есть так как кодген не готов полностью).

7. Для запуска тестов, инициализируется виртуальная машина в LLVM (по идее, результаты должны быть такими же как и при обычном запуске программы, но это проще на данном этапе). У LLVM есть функции для запуска функции из IR, но они работают только с приёмом аргументов в виде параметров main-функций или когда аргумент только один :). В документации говорится, что нужно получить указатель на функцию и скастить его к типу функции и вызвать её. Так как в джаве и котлине такие касты невозможны, то пришлось использовать Foreign Functions API. Так как он не умеет вызывать функцию с неизвестным на момент компиляции числом аргументов, то пришлось сделать костыль, но всё работает приемлемо.  

8. Сравниваем актуальный и ожидаемый результат. Не забыл про точность при сравнении даблов

При кодгенерации сейчас используются следующие примитивные типы данных: Integer (int32), Real (aka double aka FP, float64) и Boolean (int1). В зависимости от системы они преобразоваться могут в какие-то другие типы (например, бул в int32). Можно пересмотреть будет это, если будет потребность

### Что нужно сделать ещё
* Кодгенерация для всех конструкций языка, в том числе структур, циклов, бинарных операторов. 
* Лаунчер для программ (в соответствии с заданием, чтобы можно было бинарник запускать с любой рутины)
* Научиться собирать объектные файлы вместе с libc
* Нужен будет чекер на то, что длинна массива это константное значение (в соответствии с заданием). Добавил класс для этого чекера — хорошая идея, Женя
* Возможно: поддержка отладки, в LLVM это не сложно сделать
* Возможно: поддержка `print()` из libc, но это не просто будет, так как у нас только числовые и логический типы данных
*

2024-03-16 19:23 UTC, vldF commented
Ещё, добавил пресеты для запуска тестов. Пользуемся :) 
<img width="819" alt="image" src="https://github.com/vldF/i-lang-compiler/assets/21011268/250058d7-e80e-4dd0-88f3-e8487f0aecad">

2024-03-17 12:08 UTC, ebukreev requested changes

2024-03-17 12:08 UTC, ebukreev commented on src/main/kotlin/edu/itmo/ilang/ir/Declarations.kt
> +    val isUnitReturnType = type.returnType !is UnitType
называется isUnit, а проверка not is Unit

2024-03-17 12:08 UTC, ebukreev commented on src/main/kotlin/edu/itmo/ilang/semantic/checkers/ArrayIndexIsCompileTimeConstantChecker.kt
> +class ArrayIndexIsCompileTimeConstantChecker : Checker {
А что должен проверять этот класс? В доке сказано, что compile time constant нужен только при объявлении типа массива. Мы пытаемся его проевалюировать в IrBuilder, иначе репортим ошибку. Про доступ к массиву такого ограничения нет. Например, так нельзя было бы пробегаться по массиву в цикле

2024-03-17 12:08 UTC, ebukreev commented on src/main/kotlin/edu/itmo/ilang/semantic/SemanticStageProcessor.kt
> +//        ImplicitReturnTransformer(), we don't need it now
в итоге не понадобился? давай тогда удалим

2024-03-17 12:08 UTC, ebukreev commented on src/test/resources/testdata/fact.il
> +    return 1
эта правка еще нужна?

2024-03-17 12:08 UTC, ebukreev commented on src/main/kotlin/edu/itmo/ilang/codegen/CodeGenerator.kt
> +    inner class PrimaryTypes {
Не влияет: может перенести оба inner класса наверх? А то их сложно найти после приватных функций

2024-03-17 12:08 UTC, ebukreev commented on src/main/kotlin/edu/itmo/ilang/codegen/CodeGenerator.kt
> +    fun dispose() {
может реализовать Closeable? Чтобы потом можно было делать use. Или вообще вызывать этот метод в конце generate, чтобы не нужно было дергать его снаружи

2024-03-17 12:08 UTC, ebukreev commented on src/main/kotlin/edu/itmo/ilang/codegen/CodeGenerator.kt
> +class CodeGenerator {
а не хочешь реализовать IrProcessor, чтобы было видно, какие еще сущности надо обойти?

2024-03-17 12:08 UTC, ebukreev commented on src/main/kotlin/edu/itmo/ilang/codegen/CodeGenerator.kt
> +                    "and"
or

2024-03-17 12:08 UTC, ebukreev commented on src/main/kotlin/edu/itmo/ilang/codegen/CodeGenerator.kt
> +                    "and"
xor

2024-03-17 21:08 UTC, vldF commented on src/main/kotlin/edu/itmo/ilang/ir/Declarations.kt
> +    val isUnitReturnType = type.returnType !is UnitType
Она не используется сейчас. Понял, вычеркиваю

2024-03-17 21:10 UTC, vldF commented on src/main/kotlin/edu/itmo/ilang/semantic/checkers/ArrayIndexIsCompileTimeConstantChecker.kt
> +class ArrayIndexIsCompileTimeConstantChecker : Checker {
> Мы пытаемся его проевалюировать в IrBuilder, иначе репортим ошибку

Вот это бы хотелось проверять тут и показывать какую-то более очевидную ошибку, а не падать в каких-то недрах компилятора. Действительно, нужно было уточнить это, по названию не понятно. Немного подправил его

2024-03-17 21:11 UTC, vldF commented on src/main/kotlin/edu/itmo/ilang/semantic/checkers/ArrayIndexIsCompileTimeConstantChecker.kt
> +class ArrayIndexIsCompileTimeConstantChecker : Checker {
Если есть возражения — могу убрать его, мне не принципиально, просто кажется, что нам бы меньше взрывать компилятор исключениями и больше выводить понятные сообщения об ошибках

2024-03-17 21:11 UTC, vldF commented on src/main/kotlin/edu/itmo/ilang/semantic/SemanticStageProcessor.kt
> +//        ImplicitReturnTransformer(), we don't need it now
Ага, но подумал, что может понадобиться позже. Выпиливаю

2024-03-17 21:13 UTC, vldF commented on src/test/resources/testdata/fact.il
> +    return 1
Откатил

2024-03-17 21:18 UTC, vldF commented on src/main/kotlin/edu/itmo/ilang/codegen/CodeGenerator.kt
> +    fun dispose() {
> Или вообще вызывать этот метод в конце generate

Нельзя — билдер и контекст используются неявно при интерпретации

> может реализовать Closeable? Чтобы потом можно было делать use

Можно, изначально сделал так так как был еще и метод инициализации всей этой системы. Симметричнее выглядело, когда был метод инициализации и деинициализации

2024-03-17 21:19 UTC, vldF commented on src/main/kotlin/edu/itmo/ilang/codegen/CodeGenerator.kt
> +    fun dispose() {
Какой же там страшный код под капотом

<img width="962" alt="image" src="https://github.com/vldF/i-lang-compiler/assets/21011268/acc872a0-c2cc-4d0f-bfe0-42fc77541ab9">

2024-03-17 21:24 UTC, vldF commented on src/main/kotlin/edu/itmo/ilang/codegen/CodeGenerator.kt
> +class CodeGenerator {
Это было бы логично, но тут не всегда понятно, какой тип должен быть в качестве типового параметра `T`. Некоторые функции (например, для процессинга объявлений и тела) не возвращают ничего и только генерируют код. Другие возвращают LLVMValueRef (процессинги для выражений), и дальше будет больше таких различий. По этому, я отказался от этой идеи

2024-03-17 21:28 UTC, vldF commented on src/main/kotlin/edu/itmo/ilang/codegen/CodeGenerator.kt
> +    inner class PrimaryTypes {
Мне почему-то казалось, что по кодстайлу они должны быть всегда внизу. И по логике тут не обязательно понимать, что iZero это integer zero, а раз оно в constants, то это константа ноль. Но уточнил и в кодстайле написано, что inner классы в случае, если они нужны извне, идут после companion objects (то есть в конце), или идут там где они должны быть логически. Так что, вынес их на верх, под поля. Думаю, что там не очень плохо они выглядят, хотя, если будет совсем больше кода, то я вынесу их вовне куда-нибудь. Передавать контекст звучит не очень сложно и костыльно

2024-03-17 23:11 UTC, donebd commented
> Поменял структуру тестов и добавил тесты для кодогенерации. Теперь структура выглядит очевиднее так как файлы с логикой не мешаются с файлами с тестами. Кодгенератор теперь знает не про имя тест-раннера, а про конкретный инстанс класса. Это поможет при рефакторингах держать код неразломаным.
> 
> Тесты кодгенерации выглядят сложными, но работают следующим образом:
> 
> 1. Парсим программу, получаем IR представление и запускаем проверки/анализ на них — в данный момент нужен
>    только анализ завершаемости блоков, но возможно, что в будущем будет что-то ещё.
> 2. Генерируем IR LLVM при помощи класса-генератора `CodeGenerator`. В нём есть функция для компиляции представления в объектный файл, она работает, но не нужна сейчас. Оставил её на будущее.
> 3. После генерации происходит валидация функций и модуля. Если она падает, то выводится на экран какое-то описание проблемы и исключение бросается. Еще, выводится текстовое представление IR в консоль. К сожалению, сложно его вытащить как-то адекватно, у библиотеки LLVM просто нет такой функции. Есть еще функции для просмотра CFG, но их нельзя настроить никак и они просто открывают dot файл в приложении по-умолчанию в системе — там какая-то ерунда была все разы пока я смотрел, наверное, это бесполезно.
> 4. Из файла с исходником для теста считывается мета-информация для запуска теста. Решил её хранить прямо в файле с исходником, так как это не будет создавать кучу файлов (если бы я хранил её в отдельных файлах) и при этом и код, и данные видны на одном экране сразу же. Формат следующий: `имя_функции(аргумент1, аргумент2, ...)[: возвращаемый_результат]`. Доступны только примитивные типы, добавить пользовательские можно, но не хочется. Если возвращаемый тип не указан, то считаем, что там `unit`. Можно указать несколько таких строчек, тогда тест будет запущен для каждой из них. Если нет ни одной, то при тесте просто проверится, что никаких исключений при генерации кода не было (сейчас они есть так как кодген не готов полностью).
> 5. Для запуска тестов, инициализируется виртуальная машина в LLVM (по идее, результаты должны быть такими же как и при обычном запуске программы, но это проще на данном этапе). У LLVM есть функции для запуска функции из IR, но они работают только с приёмом аргументов в виде параметров main-функций или когда аргумент только один :). В документации говорится, что нужно получить указатель на функцию и скастить его к типу функции и вызвать её. Так как в джаве и котлине такие касты невозможны, то пришлось использовать Foreign Functions API. Так как он не умеет вызывать функцию с неизвестным на момент компиляции числом аргументов, то пришлось сделать костыль, но всё работает приемлемо.
> 6. Сравниваем актуальный и ожидаемый результат. Не забыл про точность при сравнении даблов
> 
> При кодгенерации сейчас используются следующие примитивные типы данных: Integer (int32), Real (aka double aka FP, float64) и Boolean (int1). В зависимости от системы они преобразоваться могут в какие-то другие типы (например, бул в int32). Можно пересмотреть будет это, если будет потребность
> 
> ### Что нужно сделать ещё
> * Кодгенерация для всех конструкций языка, в том числе структур, циклов, бинарных операторов.
> * Лаунчер для программ (в соответствии с заданием, чтобы можно было бинарник запускать с любой рутины)
> * Научиться собирать объектные файлы вместе с libc
> * Нужен будет чекер на то, что длинна массива это константное значение (в соответствии с заданием). Добавил класс для этого чекера — хорошая идея, Женя
> * Возможно: поддержка отладки, в LLVM это не сложно сделать
> * Возможно: поддержка `print()` из libc, но это не просто будет, так как у нас только числовые и логический типы данных

![image](https://github.com/vldF/i-lang-compiler/assets/55058233/e5a7c29d-a8ee-4f95-a3fc-37eeb669ced5)

2024-03-17 23:12 UTC, donebd commented on .github/workflows/tests.yml
> +        # todo: remove excludeTests param when all codegen tests will be green
Тесты грин щас?

2024-03-17 23:14 UTC, donebd commented on loader.cpp
> +}
Этот файлик используется еще?

2024-03-18 05:14 UTC, vldF commented on .github/workflows/tests.yml
> +        # todo: remove excludeTests param when all codegen tests will be green
Ага

<img width="920" alt="image" src="https://github.com/vldF/i-lang-compiler/assets/21011268/947f93ea-f10e-462f-ad3e-58ef3d47b2d8">

2024-03-18 05:15 UTC, vldF commented on loader.cpp
> +}
Пускай пока будет — единственный способ полностью скомпилировать и собрать код на i-lang сейчас

2024-03-18 05:56 UTC, ebukreev commented on src/main/kotlin/edu/itmo/ilang/semantic/checkers/ArrayIndexIsCompileTimeConstantChecker.kt
> +class ArrayIndexIsCompileTimeConstantChecker : Checker {
В текущей реализации мы не сможем присвоить ArrayType не константу, потому что там тип поля size это Int?. Поэтому непонятно, как такие ситуации (когда в индексе рандомное выражение) протаскивать от IrBuilder до этапа чекеров. Можно сделать типом поля size Expression? и пытаться эвалюировать его на этапе семантических чеков.

Но сейчас мы же не падаем если там рандомное выражение, а вызываем report в CompileTimeEvaluator. В чекере мы бы вызывали такой же метод) Мне кажется это нормально, что репортятся ошибки прямо во время построения IR, а не откладываются на потом

2024-03-18 05:57 UTC, ebukreev commented on .github/workflows/tests.yml
> +        # todo: remove excludeTests param when all codegen tests will be green
они щас грин именно из-за этой правки) локально не грин

2024-03-18 05:58 UTC, ebukreev approved these changes

2024-03-18 08:57 UTC, vldF commented on .github/workflows/tests.yml
> +        # todo: remove excludeTests param when all codegen tests will be green
Если вопрос был про это, то да — там же кодгенератор не все инструкции поддерживает. Проходит на этой ветке, вроде, 4 теста, а на моей новой ветке еще несколько. Приходится вот так вливать. Но я сделал пресеты для запуска тестов, из-за этого локально будет все ок. Делать какой-то механизм для игнорирования NotImplementedYet исключений неправильно было бы, а как-то саппрессить тесты не хотелось

Изначально подумал что раз вопрос про конфиг пайплайна, то и вопрос про них

2024-03-18 09:00 UTC, vldF commented on src/main/kotlin/edu/itmo/ilang/semantic/checkers/ArrayIndexIsCompileTimeConstantChecker.kt
> +class ArrayIndexIsCompileTimeConstantChecker : Checker {
> чекере мы бы вызывали такой же метод

Я бы кстати предложил сделать инфраструктуру для репортинга ошибок не исключениями где это возможно (исключения все-таки стоит использовтаь там, где ошибка в тех же контрактах между разными стадиями анализа, там они ок)

> Мне кажется это нормально, что репортятся ошибки прямо во время построения IR, а не откладываются на потом

Окей. Тогда уберу этот чекер как невостребованный

2024-03-18 10:56 UTC, merged